'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AllRequests
    Public Property Id As Integer
    Public Property Page As String
    Public Property Request As String
    Public Property Response As String
    Public Property Required As Date

End Class
